version: "3.3"
services:

  mysql:
    image: mysql:5.7.22
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
      MYSQL_ROOT_HOST: '%'
