server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/tictactoe?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true
    username: root
    password: rootpassword
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      initialization-fail-timeout: 0

logging:
  level:
    com.tictactoe: debug
